name: GitHub Classroom 自动评分

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: 自动评分
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pytest numpy matplotlib
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: 运行自动评分
        id: autograder
        run: python .github/classroom/autograding.py
        
      - name: 上传分数
        uses: actions/upload-artifact@v4
        with:
          name: autograder-results
          path: |
            score.json
            score_summary.md